import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import "bootstrap-icons/font/bootstrap-icons.css";
import { HeroUIProvider } from "@heroui/system";
import { Merriweather } from "next/font/google";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"]  
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pereira Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <HeroUIProvider className="Main">
          <NavBar/>
            <main className="grow bg-[#031825]">
              {children}
            </main>               
        </HeroUIProvider>                   
      </body>
    </html>
  );
}
